//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class FindBuddyMatch : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FindBuddyMatch(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FindBuddyMatch obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FindBuddyMatch() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_FindBuddyMatch(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool match(string token, Buddy buddy) {
    bool ret = (SwigDerivedClassHasMethod("match", swigMethodTypes0) ? pjsua2PINVOKE.FindBuddyMatch_matchSwigExplicitFindBuddyMatch(swigCPtr, token, Buddy.getCPtr(buddy)) : pjsua2PINVOKE.FindBuddyMatch_match(swigCPtr, token, Buddy.getCPtr(buddy)));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FindBuddyMatch() : this(pjsua2PINVOKE.new_FindBuddyMatch(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("match", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateFindBuddyMatch_0(SwigDirectormatch);
    pjsua2PINVOKE.FindBuddyMatch_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(FindBuddyMatch));
    return hasDerivedMethod;
  }

  private bool SwigDirectormatch(string token, global::System.IntPtr buddy) {
    return match(token, new Buddy(buddy, false));
  }

  public delegate bool SwigDelegateFindBuddyMatch_0(string token, global::System.IntPtr buddy);

  private SwigDelegateFindBuddyMatch_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(string), typeof(Buddy) };
}
