//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MathStat : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MathStat(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MathStat obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MathStat() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_MathStat(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int n {
    set {
      pjsua2PINVOKE.MathStat_n_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.MathStat_n_get(swigCPtr);
      return ret;
    } 
  }

  public int max {
    set {
      pjsua2PINVOKE.MathStat_max_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.MathStat_max_get(swigCPtr);
      return ret;
    } 
  }

  public int min {
    set {
      pjsua2PINVOKE.MathStat_min_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.MathStat_min_get(swigCPtr);
      return ret;
    } 
  }

  public int last {
    set {
      pjsua2PINVOKE.MathStat_last_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.MathStat_last_get(swigCPtr);
      return ret;
    } 
  }

  public int mean {
    set {
      pjsua2PINVOKE.MathStat_mean_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.MathStat_mean_get(swigCPtr);
      return ret;
    } 
  }

  public MathStat() : this(pjsua2PINVOKE.new_MathStat(), true) {
  }

}
