//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pj_file_access {
  PJ_O_RDONLY = 0x1101,
  PJ_O_WRONLY = 0x1102,
  PJ_O_RDWR = 0x1103,
  PJ_O_APPEND = 0x1108
}
