//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pj_qos_wmm_prio {
  PJ_QOS_WMM_PRIO_BULK_EFFORT,
  PJ_QOS_WMM_PRIO_BULK,
  PJ_QOS_WMM_PRIO_VIDEO,
  PJ_QOS_WMM_PRIO_VOICE
}
