//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_aud_dev_id {
  PJMEDIA_AUD_DEFAULT_CAPTURE_DEV = -1,
  PJMEDIA_AUD_DEFAULT_PLAYBACK_DEV = -2,
  PJMEDIA_AUD_INVALID_DEV = -3
}
