//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsip_tsx_state_e {
  PJSIP_TSX_STATE_NULL,
  PJSIP_TSX_STATE_CALLING,
  PJSIP_TSX_STATE_TRYING,
  PJSIP_TSX_STATE_PROCEEDING,
  PJSIP_TSX_STATE_COMPLETED,
  PJSIP_TSX_STATE_CONFIRMED,
  PJSIP_TSX_STATE_TERMINATED,
  PJSIP_TSX_STATE_DESTROYED,
  PJSIP_TSX_STATE_MAX
}
