//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsip_dialog_cap_status {
  PJSIP_DIALOG_CAP_UNSUPPORTED = 0,
  PJSIP_DIALOG_CAP_SUPPORTED = 1,
  PJSIP_DIALOG_CAP_UNKNOWN = 2
}
