//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsip_role_e {
  PJSIP_ROLE_UAC,
  PJSIP_ROLE_UAS,
  PJSIP_UAC_ROLE = PJSIP_ROLE_UAC,
  PJSIP_UAS_ROLE = PJSIP_ROLE_UAS
}
