//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsip_redirect_op {
  PJSIP_REDIRECT_REJECT,
  PJSIP_REDIRECT_ACCEPT,
  PJSIP_REDIRECT_ACCEPT_REPLACE,
  PJSIP_REDIRECT_PENDING,
  PJSIP_REDIRECT_STOP
}
