//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsua_100rel_use {
  PJSUA_100REL_NOT_USED,
  PJSUA_100REL_MANDATORY,
  PJSUA_100REL_OPTIONAL
}
