//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsua_vid_req_keyframe_method {
  PJSUA_VID_REQ_KEYFRAME_SIP_INFO = 1,
  PJSUA_VID_REQ_KEYFRAME_RTCP_PLI = 2
}
