//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsua_state {
  PJSUA_STATE_NULL,
  PJSUA_STATE_CREATED,
  PJSUA_STATE_INIT,
  PJSUA_STATE_STARTING,
  PJSUA_STATE_RUNNING,
  PJSUA_STATE_CLOSING
}
