//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsua_snd_dev_mode {
  PJSUA_SND_DEV_SPEAKER_ONLY = 1,
  PJSUA_SND_DEV_NO_IMMEDIATE_OPEN = 2
}
