//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pj_constants_ {
  PJ_SUCCESS = 0,
  PJ_TRUE = 1,
  PJ_FALSE = 0
}
