//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_srtp_keying_method {
  PJMEDIA_SRTP_KEYING_SDES,
  PJMEDIA_SRTP_KEYING_DTLS_SRTP,
  PJMEDIA_SRTP_KEYINGS_COUNT
}
