//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_srtp_crypto_option {
  PJMEDIA_SRTP_NO_ENCRYPTION = 1,
  PJMEDIA_SRTP_NO_AUTHENTICATION = 2
}
