//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_rtcp_fb_type {
  PJMEDIA_RTCP_FB_ACK,
  PJMEDIA_RTCP_FB_NACK,
  PJMEDIA_RTCP_FB_TRR_INT,
  PJMEDIA_RTCP_FB_OTHER
}
