//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_type {
  PJMEDIA_TYPE_NONE,
  PJMEDIA_TYPE_AUDIO,
  PJMEDIA_TYPE_VIDEO,
  PJMEDIA_TYPE_APPLICATION,
  PJMEDIA_TYPE_UNKNOWN
}
