//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsip_cred_data_type {
  PJSIP_CRED_DATA_PLAIN_PASSWD = 0,
  PJSIP_CRED_DATA_DIGEST = 1,
  PJSIP_CRED_DATA_EXT_AKA = 16
}
