//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsip_ssl_method {
  PJSIP_SSL_UNSPECIFIED_METHOD = 0,
  PJSIP_SSLV2_METHOD = 20,
  PJSIP_SSLV3_METHOD = 30,
  PJSIP_TLSV1_METHOD = 31,
  PJSIP_TLSV1_1_METHOD = 32,
  PJSIP_TLSV1_2_METHOD = 33,
  PJSIP_SSLV23_METHOD = 23
}
