//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsua_call_hold_type {
  PJSUA_CALL_HOLD_TYPE_RFC3264,
  PJSUA_CALL_HOLD_TYPE_RFC2543
}
